services:
  - type: web
    name: agente-eda-backend
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: LLM_PROVIDER
        value: gpt
      - key: OPENAI_API_KEY
        sync: false   # defina no painel do Render (Secret)
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: MPLBACKEND
        value: Agg
      - key: BACKEND_BASE_URL
        fromService:
          name: agente-eda-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL   # Render injeta a URL pública